'use client';

import { useEffect, useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import {
  LiveKitRoom,
  RoomAudioRenderer,
  useTracks,
  VideoTrack,
  useDataChannel,
} from '@livekit/components-react';
import '@livekit/components-styles';
import { Track } from 'livekit-client';
// the 42 nahuatl color words generated by adam's parser
import nahuatlData from './nahuatl_colors.json';
import { supabase } from '@/lib/supabase'

// pre-build a word → IPA map so caption lookups are instant
const ipaLookup: Record<string, string> = {};
for (const [word, data] of Object.entries(nahuatlData.dictionary)) {
  ipaLookup[word] = (data as { ipa: string; translation: string }).ipa;
}

// shape of the token returned by /api/livekit-token-nahuatl
interface LiveKitToken { token: string; url: string; room: string; }

// shape of caption messages sent by NahuatlTTS in agent.py
// nahuatl_word goes in the top line, english goes below — mirrors greek/english in Eirini
interface NahuatlCaption {
  nahuatl_word?: string;
  english?: string;
  display_ms?: number;
}

// same background pool as the other tutor pages
const BACKGROUNDS = [
  '/backgrounds/atardecer_palacio.jpg',
  '/backgrounds/mercado_dia_realista.jpg',
  '/backgrounds/bg4.jpg',
];

export default function NahuatlPage() {
  // token from the backend — null until the fetch completes
  const [tokenData, setTokenData] = useState<LiveKitToken | null>(null);
  const [error, setError] = useState<string | null>(null);
  // lock in a random background for the whole session
  const [background] = useState(() => BACKGROUNDS[Math.floor(Math.random() * BACKGROUNDS.length)]);
  const router = useRouter();

  useEffect(() => {
    // get the current user's session so we can pass their ID to the agent
    supabase.auth.getSession().then(({ data: { session } }) => {
        const userId = session?.user?.id ?? ""  // "" if not logged in (shouldn't happen, but safe fallback)

        // pass user_id as a query param so the agent can save this conversation to Supabase
        // fetch(`${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'}/api/livekit-token-nahuatl`)
        fetch(`https://spr26-team-25-production.up.railway.app/api/livekit-token-nahuatl?user_id=${userId}`)
        .then(res => res.json())
        .then(data => setTokenData(data))
        .catch(() => setError('Could not connect to the tutor. Please try again.'));
    })
  }, []);

  // show error if the backend fetch failed
  if (error) return (
    <main className="min-h-screen bg-stone-100 flex items-center justify-center">
      <p className="text-red-500">{error}</p>
    </main>
  );

  // show loading state while waiting for the token
  if (!tokenData) return (
    <main className="min-h-screen bg-stone-100 flex items-center justify-center">
      <p className="text-stone-500">Connecting to Citlali...</p>
    </main>
  );

  return (
    <main
      className="min-h-screen flex flex-col items-center justify-center relative"
      style={{ backgroundImage: `url(${background})`, backgroundSize: 'cover', backgroundPosition: 'center' }}
    >
      {/* dark overlay so the avatar and captions stay readable */}
      <div className="absolute inset-0 bg-black/40" />

      {/* back button always above livekit components */}
      <button
        onClick={() => router.push('/tutor')}
        className="absolute top-4 left-4 z-20 text-white/70 hover:text-white text-sm"
      >
        ← Back
      </button>

      <div className="relative z-10 w-full flex flex-col items-center">
        {/* LiveKitRoom manages the WebRTC connection.
            audio=true lets the student speak. video=false skips the student's camera. */}
        <LiveKitRoom
          token={tokenData.token}
          serverUrl={tokenData.url}
          connect={true}
          audio={true}
          video={false}
          className="w-full flex flex-col items-center"
        >
          {/* plays Citlali's audio stream automatically */}
          <RoomAudioRenderer />
          {/* NahuatlAvatar is a separate component because LiveKit hooks
              only work inside a LiveKitRoom */}
          <NahuatlAvatar />
        </LiveKitRoom>
      </div>
    </main>
  );
}

function NahuatlAvatar() {
  // current caption being displayed — null when nothing is showing
  const [caption, setCaption] = useState<NahuatlCaption | null>(null);
  // ref so we can cancel the auto-hide timer when a new caption arrives
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // listen for caption messages from agent.py on the shared "captions" data channel
  useDataChannel('captions', (msg) => {
    try {
      const data = JSON.parse(new TextDecoder().decode(msg.payload));
      // only update if the message has nahuatl content (ignore greek/lesson messages)
      if (data.english || data.nahuatl_word) {
        // cancel the previous hide timer so the old caption doesn't wipe out the new one
        if (timeoutRef.current) clearTimeout(timeoutRef.current);
        setCaption(data);
        // auto-hide after display_ms, calculated from word count in NahuatlTTS._send_caption
        // comment out next line so that captions stay until speaker asks something again.
        // timeoutRef.current = setTimeout(() => setCaption(null), data.display_ms ?? 5000);
      }
    } catch { /* ignore malformed messages */ }
  });

  // Simli streams the avatar video as a camera track
  const avatarTracks = useTracks(
    [{ source: Track.Source.Camera, withPlaceholder: false }],
    { onlySubscribed: true }
  );

  // look up the IPA for the current word — undefined if the word isn't in the dictionary
  const ipa = caption?.nahuatl_word ? ipaLookup[caption.nahuatl_word] : null;

  return (
    <div className="flex flex-col items-center gap-6 w-full max-w-lg px-4 pt-16">

      {/* avatar video window */}
      <div className="w-full aspect-video bg-black/30 rounded-2xl overflow-hidden backdrop-blur-sm">
        {avatarTracks.length > 0 ? (
          // render Simli's video stream once it arrives
          <VideoTrack trackRef={avatarTracks[0] as any} className="w-full h-full object-cover" />
        ) : (
          // placeholder while the avatar is loading
          <div className="w-full h-full flex flex-col items-center justify-center gap-1">
            <p className="text-white/50 text-sm">Waiting for Citlali...</p>
            <p className="text-white/30 text-xs">Nahuatl color tutor</p>
          </div>
        )}
      </div>

      {/* caption box. instruction always visible, nahuatl word + IPA + english when Citlali speaks */}
      <div className="w-full min-h-[110px] flex flex-col items-center justify-center text-center px-4 py-4 rounded-xl bg-black/40 backdrop-blur-sm gap-1">
      {/* always shown so the user knows what to do */}
      <p className="text-white/40 text-sm mb-2">Ask about any color in Nahuatl — the language of the Aztecs!</p>
      {caption && (
          <>
          {caption.nahuatl_word && (
            <div className="flex flex-col items-center">
            {/* nahuatl word — styled like greek in the greek tutor */}
            <p className="text-amber-300 text-2xl font-bold">{caption.nahuatl_word}</p>
            {/* IPA pronunciation, only shown if the word exists in nahuatl_colors.json */}
            {ipa && <p className="text-white/40 text-sm font-mono mt-0.5">{ipa}</p>}
            </div>
          )}
          {/* english explanation spoken by Citlali */}
          {caption.english && (
            <p className="text-white text-base mt-2">{caption.english}</p>
          )}
        </>
      )}
    </div>
    </div>
  );
}